config/routes.rb
Rails.application.routes.draw do

 resources :todos, only: [:index]

 resources :lists do
    resources :todos, only: [:create, :destroy]
  end

  devise_for :users

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  
end

app/models/list.rb
class List < ActiveRecord::Base

  belongs_to :user

  has_many :todos, dependent: :destroy

  validates :name, length: { minimum: 1 }, presence: true
  validates :user, presence: true

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  
  belongs_to :list

  validates :item, length: { minimum: 1 }, presence: true
  validates :list, presence: true

  def todo_timer
    days_ago = (Date.today - self.created_at.to_date).to_i
    
    if days_ago <  0
      days_ago = 0
    end

    7 - days_ago
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :lists

  def role?(base_role)
    role == base_role.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @lists = policy_scope(List)
  end

  def new
    @list = List.new
    authorize @list
  end

  def show
    @list = List.find(params[:id])
    @todos = @list.todos
    @todo = Todo.new
  end

  def create
    @list = current_user.lists.create(list_params)
    if @list.save
      flash[:notice] = "Great save!"
      redirect_to @list
    else
      flash[:error] = "Nope."
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    authorize @list
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(list_params)
    authorize @list
    redirect_to lists_path
  end

  def destroy
    @lists = List.find(params[:id])
    name = @list
    if @lists.destroy
      flash[:notice] = "\"#{name}\" is gone forever."
    else
      flash[:error] = "Something went wrong. Try again."
      render :show
    end
    authorize @list
    redirect_to @lists
  end

  private

  def list_params
    params.require(:list).permit(:todo, :name)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  respond_to :html, :js

  def new
    @list = List.find(params[:list_id])
    @todos = Todo.new
  end

  def create
    @list = List.find(params[:list_id])

    @todo = @list.todos.build(todo_params)
    @new_todo = Todo.new

    @todo.save!

    respond_with(@todo) do |f|
      f.html { redirect_to @list }
    end
  end

  def destroy
    @list = List.find(params[:list_id])

    @todo = @list.todos.find(params[:id])

    @todo.destroy
    redirect_to @list
  end

  private

  def todo_params
    params.require(:todo).permit(:completed, :item, :list)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping || Devise.mappings[:user]
  end

  def not_logged_in(&block)
  capture(&block) unless session[:user_id]
  end

  def logged_in(&block)
    capture(&block) if session[:user_id]
  end

  def todo_url_helper(todo)
    list = todo.list
    [list, todo]
  end

end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoozit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      
        <%= link_to "HOME", root_path, class: "btn btn-danger btn-lg btn-home pull-left" %>
        
        <% if current_user %>
          <%= link_to "Sign out", destroy_user_session_path, class: "btn btn-danger btn-lg btn-out pull-right", method: :delete %>
        
        <% end %>
    

      <%= yield %>

    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<h2><%= @list.name %></h2>

  <div class="col-md-8">
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-danger btn-lg btn-save' %>
      <% end %>
  </div>
  

app/views/lists/index.html.erb
<h1>Todo Lists</h1>
<% if policy(List.new).create? %>
<%= link_to "New List", new_list_path, class: 'btn btn-danger btn-lg btn-save' %><br>
<% end %>
<div class="table table-striped table-bordered table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Todo List Name</th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each do |list| %>
      <tr>
        <td><%= link_to list.name, list %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/lists/new.html.erb
<h1>Create New List</h1>

  <div class="col-md-8">
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
      </div>

      <%= f.submit "Save", class: 'btn btn-danger btn-lg btn-save' %>
      <% end %>
  </div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<%= link_to "Todo Lists", lists_path, class: 'btn btn-danger btn-lg btn-save' %>
<% if policy(@list).edit? %>
<%= link_to "Edit List", edit_list_path, class: 'btn btn-success btn-lg btn-save' %>
<% end %>
<% if policy(@list).destroy? %>
<%= link_to "Delete List", @lists, method: :delete, class: 'btn btn-success btn-lg btn-save' %>
<% end %>
<div class="table table-striped table-bordered table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>ToDo</th>
        <th>Days Working</th>
        <% if policy(@list).destroy? %>
        <th>Complete</th>
        <% end %>
      </tr>
    </thead>
    <tbody class="js-todos">
      <%= render @list.todos %>
    </tbody>
  </table>
  <%= render partial: 'todos/form', locals: { list: @list, todo: @todo } %>
</div>

app/views/todos/_form.html.erb
<% if policy(@list).create? %>
<%= form_for [list, todo], remote: true do |f| %>
  <% if todo.errors.any? %>
    <div class="alert alert-danger"
      <h4>There are <%= pluralize(todo.errors.count, "error") %>.</h4>
      <ul>
        <% todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_area :item, class: 'form-control', placeholder: "Create Todo here." %>
  </div>
  <div class="form-group">
    <%= f.submit "Save Todo", class: 'btn btn-danger btn-lg btn-save' %>
  <% end %>
  </div>
  <% end %>

app/views/todos/_todo.html.erb
<tr>
  <td><%= todo.item %>
  <td><%= todo.todo_timer %></td>
    <% if policy(@list).destroy? %>
  <td><%= link_to "Complete", [@list, todo], method: :delete, class: 'btn btn-success btn-sm btn-todo' %></td>
    <% end %>
</tr>

app/views/todos/create.js.erb
<% if @todo.valid? %>
  $('.js-todos').prepend("<%= escape_javascript(render(@todo)) %>");
  $('.new_todo').html("<%= escape_javascript(render partial: 'todos/form', locals: { list: @list, todo: @new_todo }) %>");
<% else %>
  $('.new_todo').html("<%= escape_javascript(render partial: 'todos/form', locals: { list: @list, todo: @todo }) %>");
<% end %>

app/views/todos/destroy.js.erb
<% if @todo.destroyed? %>
  $('#todo-' + <%= @todo.id %>).hide();
<% else %>
  $('#todo-' + <%= @todo.id %>).prepend("<div class='alert alert-error'><%= flash[:error] %></div>");
<% end %>

app/views/todos/edit.html.erb
<h1>Change Todo</h1>

<div class="col-md-8">
  <%= render partial: 'form', locals: { list: @list, todo: @todo } %>
</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<div class="col-md-8">
  <%= render partial: 'form', locals: { list: @list, todo: @todo } %>
</div>

app/views/welcome/about.html.erb
  <div class="container">
    <div class="main">
      <p>
        <%= link_to "orLOOZit", lists_path, class: "btn btn-success btn-xlarge" %>
      </p>
    </div>

    <div class="about">
      <p>ToDOOZit is a simple todo list</p>
       <p>with built in self-destruct.</p>
        <p>Set your list.</p>
        <p>Set your countdown.</p>
        <p>Do your stuff.</p>
    </div>

  </div>

app/views/welcome/index.html.erb
  <div>
  <%= link_to "Huh?", about_path, class: "btn btn-danger btn-lg btn-huh pull-right" %>
  </div>

  <div class="container">
    <div class="main">
      <p>
        <%= link_to "toDOOZit", lists_path, class: "btn btn-success btn-xlarge" %> 
      </p>
    </div>

    <div class="main">
      <p>
        <%= link_to "new toDOOZit", new_list_path, class: "btn btn-success btn-small" %> 
      </p>
    </div>

<div class="form">
<h2>Sign in</h2>
<div class="row">
  <div class="col-md-8">
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: "Enter email" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      </div>
      <div class="form-group">
        <% if devise_mapping.rememberable? -%>
          <%= f.label :remember_me, class: 'checkbox' do %>
            <%= f.check_box :remember_me %> Remember me
          <% end %>
          <% end %>
          <%= f.submit "Sign in", class: 'btn btn-danger btn-lg btn-save' %>
        </div>
          <div class="form-group">
            <%= render "devise/shared/links" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>